version: '3'

services:

#########################
# Setup server container
#########################
    server:
        build: ./server
        expose: 
            - 5000
        ports:
            - 5000:5000
        volumes:
            - ./server:/usr/src/app
        command: npm start

#########################
# Setup client container
#########################

    client:
        build: ./client
        expose:
            - 3000
        ports:
            - 3000:3000
        volumes:
            - ./client:/usr/src/app
        links:
            - server
        command: npm start

